# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proje.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time

import requests
from bs4 import BeautifulSoup

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QTextEdit, QLabel, QPushButton, QVBoxLayout, QFileDialog, QHBoxLayout
from PyQt5.QtWidgets import QAction, qApp, QMainWindow



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 767)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 771, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.baslik = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.baslik.setFont(font)
        self.baslik.setObjectName("baslik")

        self.verticalLayout.addWidget(self.baslik)

        self.dolar_tl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dolar_tl.setFont(font)
        self.dolar_tl.setObjectName("dolar_tl")

        self.verticalLayout.addWidget(self.dolar_tl)

        self.h_box_dolar_tl = QtWidgets.QHBoxLayout()
        self.h_box_dolar_tl.setObjectName("h_box_dolar_tl")

        self.dolar_tl2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dolar_tl2.setFont(font)
        self.dolar_tl2.setObjectName("dolar_tl2")

        self.h_box_dolar_tl.addWidget(self.dolar_tl2)

        self.dolar_tl_miktar = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dolar_tl_miktar.setFont(font)
        self.dolar_tl_miktar.setObjectName("dolar_tl_miktar")

        self.dolar_tl_miktar.setFixedSize(300, 30)

        self.h_box_dolar_tl.addWidget(self.dolar_tl_miktar)

        self.dolar_tl_cevir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dolar_tl_cevir.setFont(font)
        self.dolar_tl_cevir.setObjectName("dolar_tl_cevir")

        self.h_box_dolar_tl.addWidget(self.dolar_tl_cevir)

        self.dolar_tl_sonuc = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dolar_tl_sonuc.setFont(font)
        self.dolar_tl_sonuc.setObjectName("dolar_tl_sonuc")

        self.h_box_dolar_tl.addWidget(self.dolar_tl_sonuc)

        self.verticalLayout.addLayout(self.h_box_dolar_tl)

        self.dolar_tl_cevir.clicked.connect(self.f_dolar_tl)

        self.tl_dolar = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tl_dolar.setFont(font)
        self.tl_dolar.setObjectName("tl_dolar")

        self.verticalLayout.addWidget(self.tl_dolar)

        self.h_box_tl_dolar = QtWidgets.QHBoxLayout()
        self.h_box_tl_dolar.setObjectName("h_box_tl_dolar")

        self.tl_dolar2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tl_dolar2.setFont(font)
        self.tl_dolar2.setObjectName("tl_dolar2")

        self.h_box_tl_dolar.addWidget(self.tl_dolar2)

        self.tl_dolar_miktar = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tl_dolar_miktar.setFont(font)
        self.tl_dolar_miktar.setObjectName("tl_dolar_miktar")

        self.tl_dolar_miktar.setFixedSize(300, 30)

        self.h_box_tl_dolar.addWidget(self.tl_dolar_miktar)

        self.tl_dolar_cevir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tl_dolar_cevir.setFont(font)
        self.tl_dolar_cevir.setObjectName("tl_dolar_cevir")

        self.h_box_tl_dolar.addWidget(self.tl_dolar_cevir)

        self.tl_dolar_sonuc = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tl_dolar_sonuc.setFont(font)
        self.tl_dolar_sonuc.setObjectName("tl_dolar_sonuc")

        self.h_box_tl_dolar.addWidget(self.tl_dolar_sonuc)

        self.verticalLayout.addLayout(self.h_box_tl_dolar)

        self.tl_dolar_cevir.clicked.connect(self.f_tl_dolar)

        self.euro_tl = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.euro_tl.setFont(font)
        self.euro_tl.setObjectName("euro_tl")

        self.verticalLayout.addWidget(self.euro_tl)

        self.h_box_euro_tl = QtWidgets.QHBoxLayout()
        self.h_box_euro_tl.setObjectName("h_box_euro_tl")

        self.euro_tl2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.euro_tl2.setFont(font)
        self.euro_tl2.setObjectName("euro_tl2")

        self.h_box_euro_tl.addWidget(self.euro_tl2)

        self.euro_tl_miktar = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.euro_tl_miktar.setFont(font)
        self.euro_tl_miktar.setObjectName("euro_tl_miktar")

        self.euro_tl_miktar.setFixedSize(300, 30)

        self.h_box_euro_tl.addWidget(self.euro_tl_miktar)

        self.euro_tl_cevir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.euro_tl_cevir.setFont(font)
        self.euro_tl_cevir.setObjectName("euro_tl_cevir")

        self.h_box_euro_tl.addWidget(self.euro_tl_cevir)

        self.euro_tl_sonuc = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.euro_tl_sonuc.setFont(font)
        self.euro_tl_sonuc.setObjectName("euro_tl_sonuc")

        self.h_box_euro_tl.addWidget(self.euro_tl_sonuc)

        self.verticalLayout.addLayout(self.h_box_euro_tl)

        self.euro_tl_cevir.clicked.connect(self.f_euro_tl)

        self.tl_euro = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tl_euro.setFont(font)
        self.tl_euro.setObjectName("tl_euro")

        self.verticalLayout.addWidget(self.tl_euro)

        self.h_box_tl_euro = QtWidgets.QHBoxLayout()
        self.h_box_tl_euro.setObjectName("h_box_tl_euro")

        self.tl_euro2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tl_euro2.setFont(font)
        self.tl_euro2.setObjectName("tl_euro2")

        self.h_box_tl_euro.addWidget(self.tl_euro2)

        self.tl_euro_miktar = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tl_euro_miktar.setFont(font)
        self.tl_euro_miktar.setObjectName("tl_euro_miktar")

        self.tl_euro_miktar.setFixedSize(300, 30)

        self.h_box_tl_euro.addWidget(self.tl_euro_miktar)

        self.tl_euro_cevir = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tl_euro_cevir.setFont(font)
        self.tl_euro_cevir.setObjectName("tl_euro_cevir")

        self.h_box_tl_euro.addWidget(self.tl_euro_cevir)

        self.tl_euro_sonuc = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tl_euro_sonuc.setFont(font)
        self.tl_euro_sonuc.setObjectName("tl_euro_sonuc")

        self.h_box_tl_euro.addWidget(self.tl_euro_sonuc)

        self.verticalLayout.addLayout(self.h_box_tl_euro)

        self.tl_euro_cevir.clicked.connect(self.f_tl_euro)

        self.doviz = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doviz.setFont(font)
        self.doviz.setObjectName("doviz")

        self.verticalLayout.addWidget(self.doviz)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "DÖVİZ PROGRAMI"))

        self.baslik.setText(_translate("MainWindow", "                                DÖVİZ PROGRAMI"))

        self.dolar_tl.setText(_translate("MainWindow", "                                                     DOLAR  -->  TL"))
        self.dolar_tl2.setText(_translate("MainWindow", " DOLAR MİKTARI GİRİNİZ   ->  "))
        self.dolar_tl_cevir.setText(_translate("MainWindow", "$>TL ÇEVİR"))
        self.dolar_tl_sonuc.setText(_translate("MainWindow", "                       "))

        self.tl_dolar.setText(_translate("MainWindow", "                                                     TL  -->  DOLAR"))
        self.tl_dolar2.setText(_translate("MainWindow", " TL MİKTARI GİRİNİZ   ->  "))
        self.tl_dolar_cevir.setText(_translate("MainWindow", "TL>$ ÇEVİR"))
        self.tl_dolar_sonuc.setText(_translate("MainWindow", "                       "))

        self.euro_tl.setText(_translate("MainWindow", "                                                     EURO  -->  TL"))
        self.euro_tl2.setText(_translate("MainWindow", " EURO MİKTARI GİRİNİZ   ->  "))
        self.euro_tl_cevir.setText(_translate("MainWindow", "EU>TL ÇEVİR"))
        self.euro_tl_sonuc.setText(_translate("MainWindow", "                       "))

        self.tl_euro.setText(_translate("MainWindow", "                                                     TL  -->  EURO"))
        self.tl_euro2.setText(_translate("MainWindow", " TL MİKTARI GİRİNİZ   ->  "))
        self.tl_euro_cevir.setText(_translate("MainWindow", "TL>EU ÇEVİR"))
        self.tl_euro_sonuc.setText(_translate("MainWindow", "                       "))
        
        self.dovizler()

    def dovizler(self):
        url = "https://kur.doviz.com"
        response = requests.get(url)
        html_icerik = response.content
        soup = BeautifulSoup(html_icerik, "html.parser")

        birim = soup.find_all("span", {"class": "name"})
        deger = soup.find_all("span", {"class": "value"})

        liste_doviz = []
        for i, j in zip(birim,deger):
            liste_doviz.append(f"{i.text} : {j.text}")

        self.liste_birim = []
        self.liste_deger = []
        for i, j in zip(birim, deger):
            self.liste_birim.append(i.text)
            self.liste_deger.append((j.text).replace(",","."))

        # all_list = []
        # for i, j in zip(self.liste_birim, self.liste_deger):
        #     all_list.append(f"{i} - {j}")

        # for i in enumerate(all_list):
        #     print(i)

        with open("dovizler.txt", "w", encoding="utf-8")as file:

            for i in liste_doviz:
                file.write(f"{i}\n")

        with open("dovizler.txt", "r", encoding="utf-8")as file:
            self.doviz.setPlainText(file.read())

    def f_dolar_tl(self):
        with open("f_dolar_tl.txt", "w", encoding="utf-8")as file:
            file.write(str(self.dolar_tl_miktar.toPlainText()))

        f_dolar_tl = 0
        with open("f_dolar_tl.txt", "r+", encoding="utf-8")as file:
            for i in file:
                f_dolar_tl += int(i)

        f_dolar_tl_sonuc = float(f_dolar_tl) * float(self.liste_deger[1])

        self.dolar_tl_sonuc.setText(str(f_dolar_tl_sonuc))

    def f_tl_dolar(self):
        with open("f_tl_dolar.txt", "w", encoding="utf-8")as file:
            file.write(str(self.tl_dolar_miktar.toPlainText()))

        f_tl_dolar = 0
        with open("f_tl_dolar.txt", "r+", encoding="utf-8")as file:
            for i in file:
                f_tl_dolar += int(i)

        f_tl_dolar_sonuc = float(f_tl_dolar) / float(self.liste_deger[1])

        self.tl_dolar_sonuc.setText(str(f_tl_dolar_sonuc))

    def f_euro_tl(self):
        with open("f_euro_tl.txt", "w", encoding="utf-8")as file:
            file.write(str(self.euro_tl_miktar.toPlainText()))

        f_euro_tl = 0
        with open("f_euro_tl.txt", "r+", encoding="utf-8")as file:
            for i in file:
                f_euro_tl += int(i)

        f_euro_tl_sonuc = float(f_euro_tl) * float(self.liste_deger[2])

        self.euro_tl_sonuc.setText(str(f_euro_tl_sonuc))

    def f_tl_euro(self):
        with open("f_tl_euro.txt", "w", encoding="utf-8")as file:
            file.write(str(self.tl_euro_miktar.toPlainText()))

        f_tl_euro = 0
        with open("f_tl_euro.txt", "r+", encoding="utf-8")as file:
            for i in file:
                f_tl_euro += int(i)

        f_tl_euro_sonuc = float(f_tl_euro) / float(self.liste_deger[2])

        self.tl_euro_sonuc.setText(str(f_tl_euro_sonuc))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())